### Schema

CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(100) NOT NULL,
  devoured TINYINT(1) NOT NULL DEFAULT '0',
  date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
